### PR TITLE
Final cleanups

### LINKED ISSUE #11: Remove usage of FORCE_COLOR env variable
Promote `babel-code-frame` (https://github.com/babel/babel/issues/4912) and upgrade dep; then remove env variable.

Please let me know if you'd be interested in this!

### PR DESCRIPTION
**Pull request by ekosz**
Closes #11

### CODE REVIEW

**Comment by ekosz** [comment]
@Timer Sorry, just got to these now.

**Comment by Timer** [comment]
We need to hold off on 096796ccc70b7fc0e6d1e128863a3e4e350034f9; it's blocked by https://github.com/babel/babel/issues/4912.

No problem though, @ekosz! Thanks for all your hard work. 👍

**Comment by ekosz** [comment]
Oh, right. Well, this is now ready to roll once that is in place. Excited for this to land!

**Comment by Timer** [comment]
ref: #11

**Comment by Timer** [comment]
Thanks!
Merged via e5208703f9b0f8f10ef091ee68db58c7a9c69e56 and 857e0d35d180bff8581db6a3abe6b832e6341e4d.

**Pull request closed without merging**
